Vsavritsky\SettingsBundle\Entity\Settings:
    type: entity
    table: vsavritsky_settings
    repositoryClass: Vsavritsky\SettingsBundle\Repository\SettingsRepository
    indexes:
        name_idx:
            columns: [ name ]
    uniqueConstraints:
        cat_name_idx:
            columns: [ category_id, name ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: VsavritskySettingsEnumType
        name:
            type: string
            length: 50
        value:
            type: text
            nullable: true
        comment:
            type: text
            nullable: true
    manyToOne:
        category:
            targetEntity: Vsavritsky\SettingsBundle\Entity\Category
